SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS vote_membre;
DROP TABLE IF EXISTS demande_vote;
DROP TABLE IF EXISTS reaction_commentaire;
DROP TABLE IF EXISTS Reaction_proposition;
DROP TABLE IF EXISTS choix;
DROP TABLE IF EXISTS vote;
DROP TABLE IF EXISTS commentaire;
DROP TABLE IF EXISTS proposition;
DROP TABLE IF EXISTS theme_groupe;
DROP TABLE IF EXISTS droit_d_un_role;
DROP TABLE IF EXISTS infos_membre;
DROP TABLE IF EXISTS droit;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS notification;
DROP TABLE IF EXISTS reaction;
DROP TABLE IF EXISTS internaute;
DROP TABLE IF EXISTS type_scrutin;
DROP TABLE IF EXISTS thematique;
DROP TABLE IF EXISTS groupe;

SET FOREIGN_KEY_CHECKS = 1;
