GRANT SELECT ON ATHLETE TO ANALYSEJO;

GRANT SELECT ON COMPOSITION_EQUIPE TO ANALYSEJO;

GRANT SELECT ON DISCIPLINE TO ANALYSEJO;

GRANT SELECT ON EQUIPE TO ANALYSEJO;

GRANT SELECT ON EVENEMENT TO ANALYSEJO;

GRANT SELECT ON HOTE TO ANALYSEJO;

GRANT SELECT ON NOC TO ANALYSEJO;

GRANT SELECT ON PARTICIPATION_INDIVIDUELLE TO ANALYSEJO;

GRANT SELECT ON PARTICIPATION_EQUIPE TO ANALYSEJO;

GRANT SELECT ON SPORT TO ANALYSEJO;

GRANT SELECT ON LOG TO ANALYSEJO;

GRANT SELECT ON MEDAILLES_NOC TO ANALYSEJO;

GRANT SELECT ON MEDAILLES_ATHLETES TO GESTIONJO;

GRANT EXECUTE ON BIOGRAPHIE TO ANALYSEJO;

GRANT EXECUTE ON RESULTATS TO ANALYSEJO;

--ne pas oublier : Donner acc�s en consultation aux vues et en ex�cution � vos proc�dures/fonctions stock�es si elles ne modifient pas la base pour AnalyseJO.
GRANT SELECT, UPDATE, INSERT, DELETE ON ATHLETE TO GESTIONJO;

GRANT SELECT, UPDATE, INSERT, DELETE ON COMPOSITION_EQUIPE TO GESTIONJO;

GRANT SELECT, UPDATE, INSERT, DELETE ON DISCIPLINE TO GESTIONJO;

GRANT SELECT, UPDATE, INSERT, DELETE ON EQUIPE TO GESTIONJO;

GRANT SELECT, UPDATE, INSERT, DELETE ON EVENEMENT TO GESTIONJO;

GRANT SELECT, UPDATE, INSERT, DELETE ON HOTE TO GESTIONJO;

GRANT SELECT, UPDATE, INSERT, DELETE ON NOC TO GESTIONJO;

GRANT SELECT, UPDATE, INSERT, DELETE ON PARTICIPATION_INDIVIDUELLE TO GESTIONJO;

GRANT SELECT, UPDATE, INSERT, DELETE ON PARTICIPATION_EQUIPE TO GESTIONJO;

GRANT SELECT, UPDATE, INSERT, DELETE ON medailles_athletes TO GESTIONJO;

GRANT SELECT, UPDATE, INSERT, DELETE ON medailles_noc TO GESTIONJO;

GRANT SELECT ON LOG TO GESTIONJO;

GRANT EXECUTE,DEBUG ON BIOGRAPHIE TO GESTIONJO;

GRANT EXECUTE,DEBUG ON RESULTATS TO GESTIONJO;

--Il aura en revanche acc�s � toutes les fonctions/proc�dures qui permettent de consulter ou modifier la base.