--vue 1
CREATE OR REPLACE VIEW MEDAILLES_ATHLETES ("IDATHLETE", "NOMATHLETE", "PRENOMATHLETE", "MEDAILLES_D_OR", "MEDAILLES_D_ARGENT", "MEDAILLES_BRONZE", "TOTAL_MEDAILLES") AS 
  SELECT 
    A.IDATHLETE,
    A.NOMATHLETE,
    A.PRENOMATHLETE,
    SUM(CASE WHEN P.MEDAILLE = 'Gold' THEN 1 ELSE 0 END) AS MEDAILLES_D_OR,
    SUM(CASE WHEN P.MEDAILLE = 'Silver' THEN 1 ELSE 0 END) AS MEDAILLES_D_ARGENT,
    SUM(CASE WHEN P.MEDAILLE = 'Bronze' THEN 1 ELSE 0 END) AS MEDAILLES_BRONZE,
    COUNT(P.MEDAILLE) AS TOTAL_MEDAILLES
FROM 
    ATHLETE A
INNER JOIN
    (
        SELECT IDATHLETE, MEDAILLE FROM PARTICIPATION_INDIVIDUELLE
        UNION ALL
        SELECT A.IDATHLETE, PE.MEDAILLE 
        FROM PARTICIPATION_EQUIPE PE
        JOIN COMPOSITION_EQUIPE CE ON PE.IDEQUIPE = CE.IDEQUIPE
        JOIN ATHLETE A ON CE.IDATHLETE = A.IDATHLETE
    ) P ON A.IDATHLETE = P.IDATHLETE
    WHERE p.medaille is not null
GROUP BY 
    A.IDATHLETE, A.NOMATHLETE, A.PRENOMATHLETE
ORDER BY 
    MEDAILLES_D_OR DESC, MEDAILLES_D_ARGENT DESC, MEDAILLES_BRONZE DESC, TOTAL_MEDAILLES DESC, 
    A.NOMATHLETE, A.PRENOMATHLETE, A.IDATHLETE
;
-- vue 2
CREATE OR REPLACE VIEW MEDAILLES_NOC ("CODENOC", "NOMNOC", "MEDAILLES_D_OR", "MEDAILLES_D_ARGENT", "MEDAILLES_BRONZE", "TOTAL_MEDAILLES") AS 
  SELECT 
    N.CODENOC,
    N.NOMNOC,
    SUM(CASE WHEN P.MEDAILLE = 'Gold' THEN 1 ELSE 0 END) AS MEDAILLES_D_OR,
    SUM(CASE WHEN P.MEDAILLE = 'Silver' THEN 1 ELSE 0 END) AS MEDAILLES_D_ARGENT,
    SUM(CASE WHEN P.MEDAILLE = 'Bronze' THEN 1 ELSE 0 END) AS MEDAILLES_BRONZE,
    COUNT(P.MEDAILLE) AS TOTAL_MEDAILLES
FROM 
    NOC N
INNER JOIN 
    (
        SELECT PI.NOC AS CODENOC, PI.MEDAILLE FROM PARTICIPATION_INDIVIDUELLE PI
        UNION ALL
        SELECT E.NOC AS CODENOC, PE.MEDAILLE 
        FROM PARTICIPATION_EQUIPE PE
        JOIN EQUIPE E ON PE.IDEQUIPE = E.IDEQUIPE
    ) P ON N.CODENOC = P.CODENOC
    WHERE p.medaille is not null
GROUP BY 
    N.CODENOC, N.NOMNOC
ORDER BY 
    MEDAILLES_D_OR DESC, MEDAILLES_D_ARGENT DESC, MEDAILLES_BRONZE DESC, TOTAL_MEDAILLES DESC, 
    N.CODENOC, N.NOMNOC
;
SELECT COUNT(*)
FROM MEDAILLES_ATHLETES;
