
CREATE OR REPLACE VIEW Italy
AS
SELECT DISTINCT
    a.nomAthlete AS nom,
    a.prenomAthlete AS prenom,
    NBORINDIV AS NBOR,
    NBARGENTINDIV AS NBARGENT,
    NBBRONZEINDIV AS NBBRONZE
FROM
    TPLUMAS.ATHLETE a
INNER JOIN
    TPLUMAS.PARTICIPATION_INDIVIDUELLE PI ON a.idAthlete = pi.idAthlete
INNER JOIN
    TPLUMAS.medailles_individuelles MI ON a.IDATHLETE = mi.idAthlete
INNER JOIN
    TPLUMAS.NOC N ON pi.noc = n.codenoc
INNER JOIN
    TPLUMAS.EVENEMENT E ON pi.IDEVENT = e.IDEVENEMENT
INNER JOIN
    TPLUMAS.HOTE H ON e.IDHOTE = h.IDHOTE

WHERE
    h.LibelleHote LIKE '1976 Summer Olympics'
AND
    n.NOMNOC = 'Italy'
ORDER BY NBOR DESC,NBARGENT DESC,NBBRONZE DESC;

SELECT SUM(NBOR) + SUM(NBARGENT) + SUM(NBBRONZE) AS "nombre de médaile"
FROM Italy;



