SET SERVEROUTPUT ON;
SELECT
    *
FROM
    ITALY;

SELECT
    *
FROM
    PARTICIPATION;
SELECT*
    FROM EPREUVEJOMONTREAL;

GRANT SELECT ON ITALY TO ANALYSEJO;
GRANT SELECT ON ITALY TO GESTIONJO;
GRANT SELECT ON PARTICIPATION TO GESTIONJO;
GRANT SELECT ON PARTICIPATION TO ANALYSEJO;
GRANT SELECT ON EPREUVEJOMONTREAL TO ANALYSEJO;
GRANT SELECT ON EPREUVEJOMONTREAL TO GESTIONJO;

SELECT NOMEVENEMENT, STATUTEVENEMENT, CODEDISCIPLINE
FROM TPLUMAS.EVENEMENT E
INNER JOIN TPLUMAS.HOTE H ON E.IDHOTE=h.IDHOTE
WHERE h.ANNEEHOTE = 1976;
MINUS
SELECT NOMEVENEMENT, STATUTEVENEMENT, CODEDISCIPLINE
FROM TPLUMAS.EVENEMENT E
INNER JOIN TPLUMAS.HOTE H ON E.IDHOTE=h.IDHOTE
WHERE h.ANNEEHOTE = 1972;

CREATE OR REPLACE FUNCTION nombreEpreuve(genre CHAR)
RETURN NUMBER
AS
nombreEpreuve NUMBER;
BEGIN
    SELECT COUNT(*) INTO nombreEpreuve
    FROM TPLUMAS.EVENEMENT E
    INNER JOIN TPLUMAS.HOTE H ON E.IDHOTE=h.IDHOTE
    WHERE h.ANNEEHOTE = 1976
    AND e.NOMEVENEMENT LIKE '%' || INITCAP(genre) ||'%';
RETURN nombreEpreuve;
END;
/
EXECUTE DBMS_OUTPUT.PUT_LINE(nombreEpreuve('mixed'));
EXECUTE DBMS_OUTPUT.PUT_LINE(nombreEpreuve('men'));
EXECUTE DBMS_OUTPUT.PUT_LINE(nombreEpreuve('women'));

GRANT EXECUTE ON nombreEpreuve TO ANALYSEJO;
GRANT EXECUTE ON nombreEpreuve TO GESTIONJO;
SELECT*
FROM EPREUVEJOMONTREAL


SELECT *
    FROM TPLUMAS.EVENEMENT E
    INNER JOIN TPLUMAS.HOTE H ON E.IDHOTE=h.IDHOTE
    WHERE h.ANNEEHOTE = 1972;


SELECT 
        COUNT(CASE WHEN nomEvenement LIKE '%Male%' THEN 1 END) * 100.0 / COUNT(*) AS ratioHomme,
        COUNT(CASE WHEN nomEvenement LIKE '%Female%' THEN 1 END) * 100.0 / COUNT(*) AS ratioFemme,
        COUNT(CASE WHEN nomEvenement LIKE '%Mixed%' THEN 1 END) * 100.0 / COUNT(*) AS ratioMixe
    FROM TPLUMAS.EVENEMENT E
    INNER JOIN TPLUMAS.HOTE H ON E.IDHOTE=h.IDHOTE
    WHERE h.ANNEEHOTE = 1976;

    WITH participation_combinee AS (
    SELECT
        pi.IdAthlete AS IdParticipant,
        pi.Resultat,
        pi.Medaille,
        pi.NOC,
        pi.IdEvent AS IdEvenement
    FROM
        TPLUMAS.PARTICIPATION_INDIVIDUELLE PI
    UNION ALL
    SELECT
        ce.IdAthlete AS IdParticipant,
        pe.Resultat,
        pe.Medaille,
        eq.NOC,
        pe.IdEvenement
    FROM
        TPLUMAS.PARTICIPATION_EQUIPE PE
    INNER JOIN
        TPLUMAS.COMPOSITION_EQUIPE CE ON PE.IdEquipe = CE.IdEquipe
    INNER JOIN
        TPLUMAS.EQUIPE EQ ON CE.IdEquipe = EQ.IdEquipe
)

SELECT nomNOc AS "Nouveau pays"
FROM TPLUMAS.NOC N
INNER JOIN participation_combinee PC ON n.codeNoc = pc.Noc
INNER JOIN EPREUVEJOMONTREAL EM ON pc.idEvenement = em.idEvenement
MINUS
SELECT nomNOc
FROM TPLUMAS.NOC N
INNER JOIN participation_combinee PC ON n.codeNoc = pc.Noc
INNER JOIN TPLUMAS.EVENEMENT E ON e.idEvenement = pc.idEvenement
INNER JOIN TPLUMAS.HOTE H ON e.idHote = E.idHote
WHERE h.ANNEEHOTE = 1972;